name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  localnet-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show runner info
        run: |
          uname -a
          docker --version || true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dev deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      # 👇 make the script executable (Windows often strips exec bit)
      - name: Make CI scripts executable (Linux)
        run: chmod +x scripts/ci/start_localnet.sh

      # 👇 run explicitly with bash to avoid "Permission denied"
      - name: Start AlgoKit LocalNet
        run: bash scripts/ci/start_localnet.sh

      - name: Run smoke tests
        run: pytest -q

