name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  localnet-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show runner info
        run: |
          uname -a
          docker --version || true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dev deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      # 👇 Inline the LocalNet bring-up; no external .sh file needed
      - name: Start AlgoKit LocalNet (inline)
        shell: bash
        run: |
          set -euo pipefail
          python -m pip install --user algokit
          export PATH="$HOME/.local/bin:$PATH"
          algokit --version || true

          echo "Starting LocalNet..."
          algokit localnet start

          echo "Waiting for algod and indexer..."
          TIMEOUT=180
          waited=0
          until curl -sS http://localhost:4001/health > /dev/null 2>&1; do
            sleep 3; waited=$((waited+3)); if [ $waited -ge $TIMEOUT ]; then echo "algod not ready"; exit 1; fi
          done
          waited=0
          until curl -sS http://localhost:8980/health > /dev/null 2>&1; do
            sleep 3; waited=$((waited+3)); if [ $waited -ge $TIMEOUT ]; then echo "indexer not ready"; exit 1; fi
          done
          echo "LocalNet is up."

      - name: Run smoke tests
        run: pytest -q
