
name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  localnet-tests:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:24.0-dind
        options: >-
          --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dev deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Start AlgoKit LocalNet
        run: scripts/ci/start_localnet.sh

      - name: Run smoke tests
        run: pytest -q
